src/sketch.lisp
I am far from sure if this is the best way to do this, but this
successfully allows you to pass in a value for the user defined slots at
make-instance time instead of defsketch time.
=> Add hack for defsketch class initarg

src/sketch.lisp
This simply doesnt emit the local-vars for members of *default-slots*
which have been overridden in bindings
=> Dont emit unused local vars in defsketch

src/font.lisp, src/resources.lisp
Use the sdl2 surface pitch when generating an OpenGL image
This should fix https://github.com/vydd/sketch/issues/51
I ended up seeing the same issue, and it turned out that the SDL surface pitch generated from sdl2-ttf was not being taken into account when sending the pixel data to OpenGL.  Essentially there are sometimes gaps in the data because the sdl2 surface gets aligned to a power-of-two row length, instead of the number of bytes in each row.
I tested locally and it fixed the issue.
If the pitch ends up being the same as the width of the surface in pixels, this should still work fine.
2nd commit:
This should fix https://github.com/vydd/sketch/issues/32
Fix handling of different byte orders on SDL_Surface when converting to GL texture
SDL_ttf is generating argb32 images, while loaded …
=> Various font/image bugfixes

README.org
The existing link to sjl's implementation of coding math videos seems to be dead. As far as I can tell this looks to be it's new home
=> Updated to readme link to an existing repository

src/sketch.lisp
Use `(setf <slot-name>) :after` method for sketch writers, use `value` instead of `slot-name instance <slot-name>` when possible.
Originally part of #87.
=> Use :after for sketch writers, accessors instead of readers for default slots

src/sketch.lisp
Originally part of https://github.com/vydd/sketch/pull/87
=> Don't capture sketch::instance in draw and prepare

src/resources.lisp
Maybe needs further work to check that arguments provided are valid names for corresponding filters, but it works :)
Maybe should be also provided for the canvas?
(Reason: I want to be able to use pixel graphics, which looks ugly with the default mag-filter.)
=> Make it possible to specify :min-filter or :mag-filter on image creation [ new feature ]

src/resources.lisp
Adds 4 optional params (x y w h) when loading image resources, to put only a part of the image into the texture.
This is how to tile a part of an image:
```lisp
(defsketch tile
((width 400) (height 400))
(let ((res (load-resource "100x100.png" :x 0 :y 0 :w 50 :h 50)))
(with-pen (make-pen :fill (crop res 0 0 100 100))
(rect 0 0 400 400))))
```
Here, only the upper left 50x50 part of the image is loaded. As `crop` (unintuivitely?) tiles the image when width or height are larger than the ones of the image, the intended effect is achieved.
=> Cut image surface on load

src/environment.lisp
Fixes https://github.com/vydd/sketch/issues/40. Note that a warning will be signaled if setting the swap interval is not supported.
Also note that in this case vsync will no longer be activated and FPS will not be limited to 60 anymore.
=> Clear SDL error when setting swap interval is not supported

src/resources.lisp
Since there is no primary method defined for `free-resource` calling it on `NIL` will signal an error, which doesn't seem to be desired:
```lisp
* (sketch::free-resource nil)
There is no primary method for the generic function
#<STANDARD-GENERIC-FUNCTION SKETCH::FREE-RESOURCE (3)>
when called with arguments
(NIL).
[Condition of type SB-PCL::NO-PRIMARY-METHOD-ERROR]
See also:
Common Lisp Hyperspec, 7.6.6.2 [:section]
```
=> Fix free-resource method for NIL

src/drawing.lisp
Applies the fix for the vao buffer number from https://github.com/vydd/sketch/issues/20.
=> Fix the buffer number

src/utils.lisp
COPY-BUFFER is only used when drawing a figure.
SRC-OFFSET and DST-OFFSET are not used, so it is safe to assume they are fixnums (they are always 0). LENGTH is the length of the static-vector which holds the cached buffer data. By ANSI it is bounded by the ARRAY-DIMENSION-LIMIT which is guaranteed to be a fixnum, so LENGTH is a fixnum too.
Tested that figures still work on this small example:
```lisp
(defpackage #:sketch-user
(:use #:cl #:sketch))
(in-package #:sketch-user)
(deffigure foo
(circle 0 10 20)
(rect 10 20 30 40))
(defsketch bar ()
(foo (in :mouse-x 0)
(in :mouse-y 0)))
(make-instance 'bar)
```
=> Optimize COPY-BUFFER (also gets rid of warnings)

src/shapes.lisp
Also, use CIRCLE instead of RECT -- that's what users will expect to see with bigger values of PEN-WEIGHT anyways.
Fixes #46.
=> Take the current PEN-WEIGHT into account when drawing points

README.org
Incorporates the feedback that @Gleefree left on my doc update, https://github.com/vydd/sketch/pull/74.
Most importantly, fixes the misleading info about the `setup` method, as described in this issue: https://github.com/Gleefre/sketch/issues/13.
=> Address Gleefre's feedback on the documentation.

src/package.lisp, src/sketch.lisp
Makes it possible to specify whether the sketch should be resizable or not by providing a binding in `defsketch`.
For example:
```lisp
(defsketch foo ((resizable t))
(text (format nil "Resizable! Current size: ~Ax~A" width height) 0 0))
```
`foo` will be resizable by default (unless it is turned off by providing `:resizable nil` to `make-intstance`)
=> Add RESIZABLE slot to the SKETCH class

README.org, src/canvas.lisp, src/image.lisp, src/package.lisp
* Adds `DRAW` method to draw images, replacing `IMAGE` function. Makes API neater. `IMAGE` is left in place for backwards-compatibility.
* Updates docs.
* Refactors `(draw canvas ...)` so that it calls `(draw image ...)`, there was shared code between them.
* Removes `DRAW-CANVAS` symbol from package export list, it's not associated with a function.
=> Switch to drawing images with DRAW method.

sketch.asd, src/bindings.lisp, src/sketch.lisp
Makes bindings more generally usable, in hope of supporting "entities" (widgets?) in future, and cleaning up the code in general.
=> Generalize bindings

src/shapes.lisp
A workaround for the `polygon` bug, for the case where the user just wants to draw a triangle: https://github.com/vydd/sketch/issues/15
Instead of trying to triangulate, just pass the triangle coordinates directly to `draw-shape`.
I used this fix to get one of my sketches working, see: https://github.com/Kevinpgalligan/sketches/blob/master/src/thesketches/snow.lisp#L60-L61
Without this fix, that sketch crashes immediately.
=> Don't triangulate polygon if it's already a triangle.

README.org, examples/control-flow.lisp, examples/package.lisp, src/package.lisp, src/sketch.lisp
- `LOOP-YES` is now `START-LOOP`
- `LOOP-NO` is now `STOP-LOOP`
- Fixes the `CONTROL-FLOW` example, exports it
=> Renames the control flow functions

src/font.lisp, src/pen.lisp, src/utils.lisp
`make-pen` and `make-font` are automatically added when `with-pen` and `with-font` are used just with constructor plists, for example:
```lisp
(with-pen (:stroke +white+ :fill +black+)
(rect 100 100 100 100))
```
=> Adds shorthand versions of with-pen and with-font

src/bindings.lisp
Makes it possible to work with sketch without :use
=> Interns defsketch accessors into the proper package

src/canvas.lisp, src/entities.lisp, src/image.lisp, src/sketch.lisp
As discussed in Discord. Benefits:
- Allows default of (0,0).
- User may wish to use translations to determine where to draw, it then becomes inelegant that they have to pass (0,0).
- x & y coordinates can be part of the object that's being drawn, e.g. an entity that has slots containing its position.
(I still have to test these changes, just submitting this 'cause it would've been a waste of time to create an issue for a change that took 5 mins).
=> Make xy keyword args in draw

README.org, examples/life.lisp, src/controllers.lisp, src/package.lisp
Including: on-click-release, on-middle-click-release, on-right-click-release, on-text and on-button.
Also, add a call to on-hover for the window, not just entities.
Also, update the docs & examples.
Relevant issue: https://github.com/vydd/sketch/issues/125
=> Add missing input-handling functions.

src/image.lisp
By default, we currently draw a border around images. This leaks the implementation details of how images are drawn (i.e. by filling a rect), instead we can let the user draw their own border if they want.
Tested:
(defsketch imagetest
((pic (load-resource "/path/to/image.png")))
(draw pic))
=> Don't draw border around images.

src/canvas.lisp, src/controllers.lisp, src/environment.lisp, src/resources.lisp, src/sketch.lisp
An attempt to fix the first render being lost due to window resizing (see: https://github.com/vydd/sketch/issues/69).
This is achieved by creating a separate `sketch-window` class so that `sketch` doesn't have to inherit from `gl-window`. That way, the slots of `sketch` can be initialized BEFORE the window gets created, and the window can be assigned the correct dimensions from the start, avoiding a resize.
Implementation notes:
* Since there may be a circular dependency between the sketch slots and the SDL2 window (specifically: trying to create textures during slot initialization would break because the OpenGL context of the window is not available yet), we have to delay their initialization. My approach is to create a skeleton `image` object, save a lambda that will do the OpenGL parts …
=> Separate sketch window class

src/controllers.lisp, src/environment.lisp, src/sketch.lisp
Removes old utilities:
DEBUG-MODE-P, EXIT-DEBUG-MODE,
%RESTART slot, \*RESTART-FRAMES\*,
GL-CATCH, DRAW-SKETCH.
Adds
%SETUP-CALLED slot,
WITH-GL-DRAW, MAYBE-CHANGE-VIEWPORT,
ON-ERROR generic function (can be exported for the user to extend).
* DEBUG-KEY-PRESSED is set only for :MOUSEBUTTONUP events, so that from one click restarts are shown only once.
* ON-ERROR is called after unwinding the stack when the debug key is not pressed. It accepts three parameters: the sketch instance, a keyword that indicates where an error occured (:SETUP or :DRAW), and the error object. The default method draws a red screen and sets (ENV-RED-SCREEN \*ENV\*) to T.
* If debug key is pressed, restarts are shown. A :RED-SCREEN restart is established, which calls ON-ERROR as if the debug key was not pressed.
=> Rewrite error handling

src/geometry.lisp, src/pen.lisp
Sets the default rule to :nonzero for backwards compatibility (setting it to :positive by default was a mistake).
=> Makes the winding rule configurable with pens

src/controllers.lisp, src/sketch.lisp
Tested it by creating a dummy sketch with the default value for `on-close` (which is now `:escape`), as well as `:space` and `nil`.
=> Remove SDL2 'scancode-' prefix from on-close parameter.

README.org, src/controllers.lisp, src/package.lisp
There's now a tree of 'on-mouse-' functions, the user can hook into them at any point. 'on-mouse-button' propagates to 'on-mouse-left' which propagates to 'on-mouse-left-up' and 'on-mouse-left-down'. Same for 'on-mouse-middle' and 'on-mouse-right'.
Keeps 'on-click', since that's a simple and common case.
Also changes the 'state' parameter of 'on-key' so that it can have values ':up' or ':down', to be consistent with the mouse interface.
Basically added print statements to all the methods and made sure they were called. (Except the middle-mouse ones, since I'm testing with a trackpad, ha).
```lisp
(defsketch mouse () (circle 10 10 10) (stop-loop))
(defmethod on-mouse-button :before ((i mouse) button state x y)
(format t "on-mouse-button: ~a ~a ~a ~a~%" button state x y))
(defmethod …
```
=> Revise input-handling interface.

README.org, src/image.lisp
Summary of changes:
- Removed some dated language ("Since 2016...", "the old way [now 7+ years ago] that defsketch worked..."). 
- Added links to installation workarounds for some systems.
- Added latest examples.
- Generally tried to cut out unnecessary words, and to move things to the most sensible place. For example, some text was included in the "Color" section that I think was originally intended to be at the start of the tutorial.
- Added description of undocumented features: configuration options for `defsketch`, font stuff.
- Added description for the parameters of some APIs.
- Fixed a bug in my description of `crop`.
- Added a self-plug to the "Made with sketch" section :smiley: 
- Removed license from the bottom (it's already in its own file).
=> Documentation

README.org
There were some typos in the doc update, including Markdown syntax instead of org-mode syntax. Woops.
=> Fixing typos.
